### ISSUE TITLE
Example setup

### ISSUE THREAD

**Issue by pezholio** [benogle/electron-jasmine#3]
I'm currently building [an electron.js app](https://github.com/theodi/edward-csvhands), and I want to do things The Right Way. However, I'm struggling to get electron-jasmine running properly. I have (currently blank) tests in a `spec` directory, but the docs don't make it clear how to structure everything. Is there an example app anywhere that I can crib from to get me started?

**Comment by benogle** [comment]
Yeah, there is an example app at https://github.com/electronjs/electron-sample. Does that foot the bill?

**Comment by pezholio** [comment]
Cool, that should give me something to go on - thanks :+1:
