### ISSUE TITLE
How to configure dependencies?

### ISSUE THREAD

**Issue by erikmellum** [benogle/electron-jasmine#4]
First off, my question may be a bit off base, so apologies if I am asking the wrong question. In the past I have used karma as my test runner, which allows you to specify a conf.js file like this: 
![image](https://cloud.githubusercontent.com/assets/6475033/9264020/2e835102-41d7-11e5-8272-2e8aaab41257.png)
 My electron app uses angular, and I kind of look at electron-jasmine as an analogy to karma+jasmine, which leads me to my question.  How do you add dependencies?
Can I inject my dependencies like angular-mocks using electron-jasmine? It would help if there were some documentation regarding this, as well as an example test. Nonetheless, I am very appreciative you put this together!

**Comment by benogle** [comment]
You can require them in your `spec-helper.js` file at the root of the specs directory.

so

``` js
require('../bower_components/angular....')
....
```

**Comment by erikmellum** [comment]
Much appreciated!
