### ISSUE TITLE
Assuming MacOS?

### ISSUE THREAD

**Issue by franciscop** [benogle/electron-jasmine#5]
It cannot execute due to this error *:

``` bash
[...]/node_modules/.bin/electron-jasmine: line 15: [...]/node_modules/electron-jasmine/../electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron
```

As you can see, it searches for `MacOS` verrsion, while I'm in Linux. So the bug seems to be: assuming MacOS

*[...] is the project path

**Comment by markfarrall** [comment]
Same issue on Windows. The path in the cli.sh doesn't exist in Windows so any call to the module gives a `The system cannot find the path specified.` error. I assume this all goes away if you use the approach in the outstanding pull request.
