### ISSUE TITLE
electron-compile 1.0.0 should be used

### ISSUE THREAD

**Issue by rhysd** [benogle/electron-jasmine#7]
electron-jasmine currently doesn't work with Electron v0.34 with removed `registerProtocol` API error.  This is because electron-compile 1.0.0 already works well but electron-jasmine depends on 0.x.
If there is no blocker, electron-jasmine should depend on electron-compile 1.0.0.

**Comment by benogle** [comment]
Fixed via 2eda1c66aa246464ca9bf1d978fab94e4a1c4534

This is out in 0.2.0

**Comment by rhysd** [comment]
Thanks!
